config/routes.rb
Rails.application.routes.draw do

  root 'home#index', as: :root

  devise_for :users
  namespace :member do
    resources :hospital_lists do
      collection do
        get :cms_provider
        get :zip_code
      end
    end
  end

  get '*path', to: redirect('/')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cms_provider_of_service.rb
# frozen_string_literal: true

class CmsProviderOfService < ApplicationRecord
  self.table_name = 'cms_provider_of_service'
end

app/models/hvhc_dim_member.rb
class HvhcDimMember < ApplicationRecord
end

app/models/member/hospital_list.rb
# frozen_string_literal: true

module Member
  class HospitalList < ApplicationRecord
    self.table_name = 'Member_hospital_list'
    self.primary_keys = :member_id, :prvdr_num_ccn

    paginates_per 2

    PER_PAGE = 2

    validates :organization_id, :member_id, :prvdr_num_ccn, presence: true
    validate :hospital_list

    def hospital_list
      if Member::HospitalList.where(member_id: self.member_id).present? || Member::HospitalList.where(prvdr_num_ccn: self.prvdr_num_ccn).present?
        errors.add(:base, 'Cannot insert duplicate key for member_id or prvdr_num_ccn in object')
      end
    end
  end
end

app/models/member/hvhc_dim.rb
# frozen_string_literal: true

module Member
  class HvhcDim < ApplicationRecord
    self.table_name = 'hvhc_dim_member'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true, email: true
  validates :role, presence: true

  enum role: %i[user admin]
end

app/models/ziphsahrr15.rb
# frozen_string_literal: true

class Ziphsahrr15 < ApplicationRecord
  self.table_name = 'ziphsahrr15'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_error

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :role])
  end

  def render_not_found_error
    flash[:error] = 'Sorry! Record Not Found'
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def index
  end
end

app/controllers/hvhc/member/hospital_lists_controller.rb
class Hvhc::Member::HospitalListsController < ApplicationController
  before_action :find_hospital, only: %i[show edit update]

  def index
    @count = ::Member::HospitalList.count
    @results = ::Member::HospitalList.page params[:page]
    @hospital_lists = @results.first(::Member::HospitalList::PER_PAGE)
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @hospital_list.update(hospital_params)
        format.html { redirect_to hvhc_member_hospital_list_path(@hospital_list.member_id), notice: 'Recipe was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def find_hospital
    @hospital_list = ::Member::HospitalList.where(member_id: params[:id]).first
  end

  def hospital_params
    params.require(:hospital_list).permit(:organization_id, :member_id, :prvdr_num_ccn,
                                          :fac_name_friendly, :fac_name, :st_adr, :city_name,
                                          :zip_cd, :zip_txt, :state_cd, :aha_id)
  end
end

app/controllers/member/hospital_lists_controller.rb
# frozen_string_literal: true

class Member::HospitalListsController < ApplicationController
  before_action :find_hospital, only: %i[show edit update destroy]

  def index
    @count = ::Member::HospitalList.count
    @results = ::Member::HospitalList.page params[:page]
    @hospital_lists = @results.first(::Member::HospitalList::PER_PAGE)
  end

  def new
    @hospital_list = ::Member::HospitalList.new
  end

  def edit
  end

  def show
  end

  def create
    @hospital_list = ::Member::HospitalList.new(hospital_params)
    if @hospital_list.save
      flash[:notice] = 'Hospital List was successfully created.'
      redirect_to member_hospital_lists_path
    else
      flash[:alert] = @hospital_list.errors.full_messages.first
      render :new
    end
  end

  def update
    respond_to do |format|
      if @hospital_list.update(hospital_params)
        format.html { redirect_to member_hospital_list_path(@hospital_list.member_id), notice: 'Hospital List was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @hospital_list.destroy
    respond_to do |format|
      format.html { redirect_to member_hospital_lists_path, notice: 'Hospital List was successfully destroyed.' }
    end
  end

  def cms_provider
    provider = CmsProviderOfService.find_by(prvdr_num: params[:prvdr_num])
    render json: { provider: provider, status: 200 }
  end

  def zip_code
    zip_code = Ziphsahrr15.find_by(zipcode15: params[:zip_code])
    render json: { zip_code: zip_code, status: 200 }
  end

  private

  def find_hospital
    @hospital_list = ::Member::HospitalList.where(member_id: params[:id]).first
  end

  def hospital_params
    params.require(:member_hospital_list).permit(:organization_id, :member_id, :prvdr_num_ccn,
                                          :cross_ref_provider_number, :prvdr_ctgry_sbtyp_cd,
                                          :prvdr_ctgry_sbtyp_cd_num, :fac_name_friendly, :fac_name,
                                          :st_adr, :city_name, :state_cd, :zip_cd, :zip_txt,
                                          :aha_sysname, :aha_id, :cms_report, :hrrnum, :hsanum,
                                          :notes, :flagship_hosp)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def page_starts_with(page_no, per_page)
    (page_no * per_page) + 1
  end

  def page_ends_with(page_no, per_page, data_count)
    (page_no * per_page) + data_count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="site_title">
      <%= image_tag 'LandingPageImage', class: 'site_title', alt: 'HVHC Applications' %>


    <p class="lead">Specialty Apps for PMO staff.....</p>
      </div>

  </div>

</div>

app/views/hvhc/member/hospital_lists/_action_list.html.erb
<div class="only-desktops" style="white-space: nowrap">
  <a class="btn btn-default btn-outline-dark" href="<%= edit_hvhc_member_hospital_list_path(hospital_list.member_id) %>">
    <i class="el el-pencil"></i>
    Edit
  </a>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-outline-dark gc-bootstrap-dropdown dropdown-toggle">
      More
      <span class="caret"></span>
    </button>
    <div class="dropdown-menu">
      <a href="<%= hvhc_member_hospital_list_path(hospital_list) %>" class="dropdown-item">
        <i class="el el-eye-open"></i> View
      </a>
      <a href="/demo/bootstrap_theme_v4/clone/103" class="dropdown-item">
        <i class="el el-fork"></i> Clone
      </a>
      <a data-target="/demo/bootstrap_theme_v4/delete/103" href="javascript:void(0)" title="Delete" class="delete-row dropdown-item">
        <i class="el el-remove text-danger"></i>
        <span class="text-danger">Delete</span>
      </a>
    </div>
  </div>
</div>

app/views/hvhc/member/hospital_lists/edit.html.erb
<div class="container gc-container edit-wrapper">
  <div class="row">
    <div class="col-md-12">
      <div class="table-label">
        <div class="floatL l5">
          Edit Hospital
        </div>
        <div class="clear"></div>
      </div>
      <div class="form-container table-container">
        <%= form_for :hospital_list, url: hvhc_member_hospital_list_path(@hospital_list.member_id), method: :patch, html: { id: 'hospital_list' } do |f| %>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Organization ID123
          </label>
          <div class="col-sm-9">
            <%= f.text_field :organization_id, value: @hospital_list.organization_id, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Member ID
          </label>
          <div class="col-sm-9">
            <%= f.text_field :member_id, value: @hospital_list.member_id, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Provider Number CCN
          </label>
          <div class="col-sm-9">
            <%= f.text_field :prvdr_num_ccn, value: @hospital_list.prvdr_num_ccn, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Fac Name Friendly
          </label>
          <div class="col-sm-9">
            <%= f.text_field :fac_name_friendly, value: @hospital_list.fac_name_friendly, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Fac Name
          </label>
          <div class="col-sm-9">
            <%= f.text_field :fac_name, value: @hospital_list.fac_name, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Street Address
          </label>
          <div class="col-sm-9">
            <%= f.text_field :st_adr, value: @hospital_list.st_adr, maxlength: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            City
          </label>
          <div class="col-sm-9">
            <%= f.text_field :city_name, value: @hospital_list.city_name, maxlength: 50, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            Zip Code
          </label>
          <div class="col-sm-9">
            <%= f.text_field :zip_cd, value: @hospital_list.zip_cd, maxlength: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group creditLimit_form_group row">
          <label class="col-sm-3 control-label">
            Zip Text
          </label>
          <div class="col-sm-9">
            <%= f.text_field :zip_txt, value: @hospital_list.zip_txt, maxlength: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            State Code
          </label>
          <div class="col-sm-9">
            <%= f.text_field :state_cd, value: @hospital_list.state_cd, maxlength: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
            AHA ID
          </label>
          <div class="col-sm-9">
            <%= f.text_field :aha_id, value: @hospital_list.aha_id, maxlength: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group gcrud-form-group">
          <div id="report-error" class="report-div error bg-danger" style="display:none"></div>
          <div id="report-success" class="report-div success bg-success" style="display:none"></div>
        </div>
        <div class="form-group gcrud-form-group button-block-field">
          <div class="col-sm-offset-3 col-sm-7">
            <button class="btn btn-secondary btn-success b10" type="submit" id="form-button-save">
              <i class="el el-ok"></i>
              Update changes
            </button>
            <button class="btn btn-info b10" type="button" id="save-and-go-back-button">
              <i class="el el-return-key"></i>
              Update and go back to list
            </button>
            <button class="btn btn-secondary cancel-button b10" type="button" id="cancel-button">
              <i class="el el-warning-sign"></i>
              Cancel
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/hvhc/member/hospital_lists/show.html.erb
<div class="container gc-container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-label">
        <div class="floatL l5">
          View Hospital
        </div>
        <div class="clear"></div>
      </div>
      <div class="form-container table-container">
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Organisation ID:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-customerName" class="readonly_label">
              <%= @hospital_list.organization_id %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Member ID:123
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-contactLastName" class="readonly_label">
              <%= @hospital_list.member_id %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Provider Number CCN:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-contactFirstName" class="readonly_label">
              <%= @hospital_list.prvdr_num_ccn %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Fac Name Friendly:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-phone" class="readonly_label">
              <%= @hospital_list.fac_name_friendly %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Fac Name:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-addressLine1" class="readonly_label">
              <%= @hospital_list.fac_name %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Street Address:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-addressLine2" class="readonly_label">
              <%= @hospital_list.st_adr %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          City Name:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-city" class="readonly_label">
              <%= @hospital_list.city_name %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Zip Code:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-state" class="readonly_label">
              <%= @hospital_list.zip_cd %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          Zip Text:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-state" class="readonly_label">
              <%= @hospital_list.zip_txt %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          State Code:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-state" class="readonly_label">
              <%= @hospital_list.state_cd %>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">
          AHA ID:
          </label>
          <div class="col-sm-9 read-row">
            <div id="field-postalCode" class="readonly_label">
              <%= @hospital_list.aha_id %>
            </div>
          </div>
        </div>

        <div class="form-group gcrud-form-group">
          <div id="report-error" class="report-div error"></div>
          <div id="report-success" class="report-div success"></div>
        </div>
        <div class="form-group gcrud-form-group">
          <div class="col-sm-offset-3 col-sm-7">
            <button class="btn btn-secondary cancel-button" type="button" onclick="window.history.back();">
              <i class="el el-return-key"></i>
              Back to list
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/member/hospital_lists/_action_list.html.erb
<div class="only-desktops" style="white-space: nowrap">
  <a class="btn btn-default btn-outline-dark" href="<%= edit_member_hospital_list_path(hospital_list.member_id) %>">
    <i class="el el-pencil"></i>
    Edit
  </a>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-outline-dark gc-bootstrap-dropdown dropdown-toggle">
      More
      <span class="caret"></span>
    </button>
    <div class="dropdown-menu">
      <a href="<%= member_hospital_list_path(hospital_list.member_id) %>" class="dropdown-item">
        <i class="el el-eye-open"></i> View
      </a>
      <!-- <a href="/demo/bootstrap_theme_v4/clone/103" class="dropdown-item">
        <i class="el el-fork"></i> Clone
      </a> -->
      <a href="<%= member_hospital_list_path(hospital_list.member_id)%>" data-method="delete" data-confirm='Are you sure? You want to delete this.' title="Delete" class="delete-row dropdown-item">
        <i class="el el-remove text-danger"></i>
        <span class="text-danger">Delete</span>
      </a>
    </div>
  </div>
</div>

app/views/member/hospital_lists/index.html.erb
<% if @hospital_lists.present? %>
  <div class="container-fluid gc-container">
    <div class="success-message hidden"></div>
    <div class="">
      <div class="table-section">
        <div class="table-label">
          <div class="floatL l5">
            Member Hospital
          </div>
          <div class="clear"></div>
        </div>
        <div class="table-container">
          <form action="" method="post" autocomplete="off" id="gcrud-search-form" accept-charset="utf-8">
            <div class="header-tools">
              <div class="floatL t5">
                <a class="btn btn-default btn-outline-dark" href="<%= new_member_hospital_list_path %>">
                  <i class="el el-plus"></i> Add Hospital
                </a>
                <a href="javascript:void(0);" class="btn btn-default btn-outline-dark gc-refresh">
                <i class="el el-refresh"></i>
                Refresh
                </a>
              </div>
              <div class="floatR">
                <a class="btn btn-default btn-outline-dark t5" data-url="" href="javascript:void(0);">
                  <i class="el el-share floatL t3"></i>
                  <span class="hidden-xs floatL l5">
                    Export
                  </span>
                  <div class="clear"></div>
                </a>
                <a class="btn btn-default btn-outline-dark t5 gc-print" data-url="" href="javascript:void(0);">
                  <i class="el el-print floatL t3"></i>
                  <span class="hidden-xs floatL l5">
                    Print
                  </span>
                  <div class="clear"></div>
                </a>
                <a class="btn search-button t5 btn-primary" href="javascript:void(0);">
                <i class="el el-search"></i>
                <input type="text" name="search" class="search-input">
                </a>
              </div>
              <div class="clear"></div>
            </div>
            <div class="scroll-if-required table-responsive hvhc-table">
              <table class="table table-bordered table-striped grocery-crud-table table-hover">
                <thead>
                  <tr>
                    <th colspan="2">
                      Actions
                    </th>
                    <th class="column-with-ordering" scope="col">Organization ID</th>
                    <!-- <th class="column-with-ordering" scope="col">Member ID</th> -->
                    <th class="column-with-ordering" scope="col">Provider Number</th>

                    <!-- <th class="column-with-ordering" scope="col">Cross Reference Provider Num</th>
                    <th class="column-with-ordering" scope="col">Provider Category SubType Code</th>
                    <th class="column-with-ordering" scope="col">Provider Category SubType Code Num</th> -->

                    <th class="column-with-ordering" scope="col">Facility Friendly</th>
                    <th class="column-with-ordering" scope="col">Facility Name</th>
                    <th class="column-with-ordering" scope="col">Street Address</th>
                    <th class="column-with-ordering" scope="col">City</th>
                    <th class="column-with-ordering" scope="col">State Code</th>
                    <th class="column-with-ordering" scope="col">Zip Code</th>
                    <!-- <th class="column-with-ordering" scope="col">Zip Text</th> -->
                    <!-- <th class="column-with-ordering" scope="col">AHA System Name</th>
                    <th class="column-with-ordering" scope="col">AHA ID</th>

                    <th class="column-with-ordering" scope="col">CMS Report</th>
                    <th class="column-with-ordering" scope="col">HRR Number</th>
                    <th class="column-with-ordering" scope="col">HSA Number</th>
                    <th class="column-with-ordering" scope="col">Notes</th>
                    <th class="column-with-ordering" scope="col">Last Updated At</th> -->
                    <th class="column-with-ordering" scope="col">FlagShip Hospital</th>
                  </tr>
                  <!-- <tr class="filter-row gc-search-row">
                    <td class="no-border-right ">
                      <div class="floatL t5">
                        <input type="checkbox" class="select-all-none">
                      </div>
                    </td>
                    <td class="no-border-left ">
                      <div class="floatL">
                        <a href="javascript:void(0);" title="Delete" class="hidden btn btn-outline-dark delete-selected-button">
                        <i class="el el-remove text-danger"></i>
                        <span class="text-danger">Delete</span>
                        </a>
                      </div>
                      <div class="">
                        <a href="javascript:void(0);" class="btn btn-default btn-outline-dark gc-refresh">
                        <i class="el el-refresh"></i>
                        Refresh
                        </a>
                      </div>
                      <div class="clear"></div>
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Organization" name="organization_id">
                    </td>
                    <!-- <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Member" name="member">
                    </td> -->
                    <!-- <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Provider" name="provider">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Cross Ref Provider Num" name="ref_prvd_num">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Provider category Subtype code" name="pvrd_cate_sub_type_code">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Provider category Subtype code Num" name="pvrd_cate_sub_type_code_num">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Fac Name Friendly" name="fac_name_friendly">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Fac Name" name="fac_name">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Street Address" name="street_address">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search City Name" name="city_name">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search State Code" name="state_code">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Zip" name="zip_code">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Zip Text" name="zip_text">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search AHA System Name" name="aha_sys_name">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search AHA" name="aha_id">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search CMS Report" name="cms_report">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search HRR Num" name="hrrnum">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search HSA Num" name="hsanum">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Notes" name="notes">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search Last Updated" name="last_date_updated">
                    </td>
                    <td>
                      <input type="text" class="form-control searchable-input floatL" placeholder="Search FlagShip" name="flagship_hosp">
                    </td>
                  </tr> -->
                </thead>
                <tbody>
                  <% @hospital_lists.each do |hospital_list| %>
                    <tr>
                      <td>
                       <input type="checkbox" class="select-row" data-id= <%= hospital_list.member_id %> />
                      </td>
                      <td><%= render 'action_list', hospital_list: hospital_list %></td>
                      <td><%= hospital_list.organization_id %></td>
                      <!-- <td><%= hospital_list.member_id %></td> -->
                      <td><%= hospital_list.prvdr_num_ccn %></td>

                      <!-- <td><%= hospital_list.cross_ref_provider_number %></td>
                      <td><%= hospital_list.prvdr_ctgry_sbtyp_cd %></td>
                      <td><%= hospital_list.prvdr_ctgry_sbtyp_cd_num %></td> -->

                      <td><%= hospital_list.fac_name_friendly %></td>
                      <td><%= hospital_list.fac_name %></td>
                      <td><%= hospital_list.st_adr %></td>
                      <td><%= hospital_list.city_name %></td>
                      <td><%= hospital_list.state_cd %></td>
                      <td><%= hospital_list.zip_cd %></td>
                      <!-- <td><%= hospital_list.zip_txt %></td> -->
                      <!-- <td><%= hospital_list.aha_sysname %></td>
                      <td><%= hospital_list.aha_id %></td> -->

                      <!-- <td><%= hospital_list.cms_report %></td>
                      <td><%= hospital_list.hrrnum %></td>
                      <td><%= hospital_list.hsanum %></td>
                      <td><%= hospital_list.notes %></td>
                      <td><%= hospital_list.last_date_updated %></td> -->
                      <td><%= hospital_list.flagship_hosp %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- Table Footer -->
            <div class="footer-tools">
              <!-- "Displaying 1 to 10 of 116 items" -->
              <div class="floatR r10 displaying-paging-items">
                <% page_no = params[:page].present? ? (params[:page].to_i - 1) : 0 %>
                Displaying <span class="paging-starts"><%= page_starts_with(page_no, ::Member::HospitalList::PER_PAGE) %></span> to
                <span class="paging-ends"><%= page_ends_with(page_no, ::Member::HospitalList::PER_PAGE, @hospital_lists.count) %></span> of
                <span class="current-total-results"><%= @count %></span> items
                <span class="full-total-container hidden">
                  (filtered from <span class="full-total"><%= @count %></span> total entries)
                </span>
              </div>
              <!-- End of "Displaying 1 to 10 of 116 items" -->
              <div class="clear"></div>
            </div>
            <!-- End of: Table Footer -->
          </form>
          <ul class="pagination mt20">
            <%= paginate @results, theme: 'twitter-bootstrap-4' %>
          </ul>
        </div>
      </div>
      <!-- Delete confirmation dialog -->
      <div class="delete-confirmation modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
              <p>Are you sure that you want to delete this record?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-danger delete-confirmation-button">Delete</button>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Delete confirmation dialog -->
    </div>
  </div>
<% else %>
  <div> No record found.</div>
<% end %>